### ISSUE TITLE
Allow for EC2 IAM Roles 

### ISSUE THREAD

**Issue by peter-trerotola** [methodin/tiger#1]
Requiring a key and secret does not allow for the use of EC2 IAM Roles and maybe complicate deployment. Any way to make these optional?

https://github.com/methodin/tiger/blob/master/src/package.rs#L54

**Comment by methodin** [comment]
Yeah in fact they have a chain provider I just don't have any setup on my own e 2 account. Can you send an example setup I can replicate?

**Comment by methodin** [comment]
Updated to use ChainProvider
